query getAllSchools {
  schools(where: { language: EN }) {
    nodes {
      id
      title
      link
      acf {
        schoolAddress
        schoolPhoneNumber
        schoolGrades
        schoolHours
        schoolZip
      }
      language {
        id
        name
      }
    }
  }
}
